live-persist: Remove bashisms from logging and switch to /bin/sh.
While we're at it, also remove some stderr null-redirections since the
output can be useful in the log files.

diff --git a/config/chroot_local-includes/usr/local/sbin/live-persist b/config/chroot_local-includes/usr/local/sbin/live-persist
--- a/config/chroot_local-includes/usr/local/sbin/live-persist
+++ b/config/chroot_local-includes/usr/local/sbin/live-persist
@@ -1,10 +1,10 @@
-#!/bin/bash
+#!/bin/sh
 
 NAME="${0##*/}"
 
 error ()
 {
-	echo "error: ${@}" >&2
+	echo "error: ${@}" >&3
 	exit 1
 }
 
@@ -53,7 +53,7 @@ override the corresponging options parsed from the kernel command-line.
 
 General options:
   -h, --help            display this help and exit
-  -l, --log-file=FILE   log the bash execution trace to FILE
+  -l, --log-file=FILE   log the execution trace to FILE
 
 Options affecting the 'list' action:
   -e, --encryption=LIST override 'persistence-encryption'
@@ -67,7 +67,7 @@ Options affecting the 'activate' action:
 
 warning ()
 {
-	echo "warning: ${@}" >&2
+	echo "warning: ${@}" >&3
 }
 
 dbus_udisks_get_attribute ()
@@ -79,7 +79,7 @@ dbus_udisks_get_attribute ()
 		/org/freedesktop/UDisks/devices/$(basename ${dev}) \
 		org.freedesktop.DBus.Properties.Get \
 		string:org.freedesktop.UDisks.Device \
-		string:"${attribute}" 2>/dev/null | \
+		string:"${attribute}" | \
 		grep -e "${re}" | sed "s|${re}|\1|"
 }
 
@@ -157,10 +157,10 @@ list_gpt_volumes ()
 
 	for dev in $(storage_devices "" "${white_listed_devices}")
 	do
-		if ( is_luks_partition ${dev} >/dev/null 2>&1 && \
+		if ( is_luks_partition ${dev} >/dev/null && \
 		     echo ${PERSISTENCE_ENCRYPTION} | grep -qve "\<luks\>" ) || \
 
-		   ( ! is_luks_partition ${dev} >/dev/null 2>&1 && \
+		   ( ! is_luks_partition ${dev} >/dev/null && \
 		     echo ${PERSISTENCE_ENCRYPTION} | grep -qve "\<none\>" )
 		then
 			continue
@@ -196,7 +196,7 @@ activate_volumes ()
 			continue
 		fi
 		local luks_vol=""
-		if /sbin/cryptsetup isLuks ${vol} >/dev/null 2>&1 
+		if /sbin/cryptsetup isLuks ${vol} >/dev/null
 		then
 			if luks_vol=$(open_luks_device "${vol}")
 			then
@@ -213,10 +213,10 @@ activate_volumes ()
 	get_custom_mounts ${custom_mounts} ${open_volumes}
 	if [ -s "${custom_mounts}" ]
 	then
-		activate_custom_mounts ${custom_mounts} &> /dev/null
+		activate_custom_mounts ${custom_mounts} >/dev/null
 		fix_gconf_dirs
 	fi
-	rm -f ${custom_mounts} 2> /dev/null
+	rm -f ${custom_mounts}
 
 	for vol in ${open_volumes}
 	do
@@ -258,10 +258,10 @@ close_volumes ()
 	do
 		if [ "${options}" != linkfiles ]
 		then
-			umount ${dest} 2> /dev/null
+			umount ${dest}
 		fi
 	done < ${custom_mounts}
-	rm -f ${custom_mounts} 2> /dev/null
+	rm -f ${custom_mounts}
 	for vol in ${volumes}
 	do
 		local backing=$(where_is_mounted ${vol})
@@ -271,17 +271,20 @@ close_volumes ()
 
 main ()
 {
-	# tracing get's activated by Arguments() if "debug" is in /proc/cmdline
-	# which may be something we don't want to flood stderr
-	exec 3<>"/dev/null"
-	BASH_XTRACEFD="3"
+	# We're gonna mess with stderr's file descriptor below, so we
+	# save a reference to it in fd 3 if we want to print to stderr
+	exec 3>&2
+
+	# tracing get's activated by Cmdline_old() if "debug" is in
+	# /proc/cmdline which will flood stderr, which we don't want
+	exec 2>"/dev/null"
 
 	# parse the kernel cmdline for live-boot's configuration as defaults
 	Cmdline_old
 
-	# note that this is not enough for disabling tracing. we need to do the
-	# $BASH_XTRACEFD stuff above to avoid tracing until this point.
+	# disable tracing if enabled by Cmdline_old()
 	set +x
+	exec 2>&3
 
 	export PERSISTENCE="true"
 	export NOPERSISTENCE=""
@@ -310,10 +313,7 @@ main ()
 				;;
 			-l|--log-file)
 				shift
-				local log_file="${1}"
-				[ -e "${log_file}" ] && rm -f "${log_file}"
-				exec 3<>"${log_file}"
-				set -x
+				DEBUG_LOG_FILE="${1}"
 				;;
 			-m|--media)
 				shift
@@ -339,6 +339,12 @@ main ()
 		esac
 		shift
 	done
+
+	if [ -n "${DEBUG_LOG_FILE}" ]
+	then
+		exec 2>"${DEBUG_LOG_FILE}"
+		set -x
+	fi
 
 	local action="${1}"
 	shift
